version: '3.1'

services:
  mariadb:
    image: mariadb
    ports:
      - "3311:3311"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: codenation
